version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: forex_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: forex_risk_mgr_db

volumes:
  mongo_data:
